version: '3.8'

services:
  agent-gateway-krakend:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentic-layer/agent-gateway-krakend:latest
    container_name: agent-gateway-krakend
    ports:
      - "8080:8080"
    volumes:
      - ./local/krakend.json:/etc/krakend/krakend.json:ro
    restart: unless-stopped
    networks:
      - agent-network

  weather-agent:
    image: ghcr.io/agentic-layer/weather-agent:main
    container_name: weather-agent
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
