apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: agent-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: weather-agent
spec:
  framework: google-adk  # Supported: google-adk, flokk, autogen
  image: eu.gcr.io/agentic-layer/weather-agent:0.1.2
  protocols:
    - type: A2A  # Agent-to-Agent protocol
  exposed: true  # Whether the agent should be exposed via the gateway
  replicas: 1  # Number of agent replicas (optional, default: 1)
  env:
    - name: PORT
      value: "8080"
  envFrom:
    - secretRef:
        name: api-key-secret